filebeat.prospectors:
  - type: log
    paths: ["/data/*"]
    fields_under_root: true
    scan_frequency: 10s

output.kafka:
  hosts: ["kafka:9092"]
  topic: "mytopic"
  partition.round_robin:
    reachable_only: true
    group_events: 100
    version: '0.10'
    client_id: filebeat
    worker: 1
    broker_timeout: 30s
    keep_alive: 60s
    compression: snappy
    channel_buffer_size: 2048
    required_acks: 1
